apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name3  }}
  labels:
    {{- include "app.label3" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabel3" . | nindent 4 }}
