apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name2  }}
  labels:
    {{- include "app.label2" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabel2" . | nindent 4 }}
